### 말뭉치 전처리

In [1]:
text = "You say goodbye and I say hello."
text = text.lower()
text = text.replace('.',' .')
print(text)

you say goodbye and i say hello .


In [2]:
words = text.split()
print(words)

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']


In [3]:
word_to_id = {} # 딕셔너리
id_to_word = {}

for word in words:
    if word in word_to_id:
        continue
    new_id = len(word_to_id)
    word_to_id[word] = new_id;
    id_to_word[new_id] = word;
    
print(word_to_id)
print(id_to_word)

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [4]:
import numpy as np

corpus = [word_to_id[w] for w in words] # 문장에 담긴 단어들을 id로 표현
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

### 말뭉치 처리 함수

In [46]:
import numpy as np

def preprocess(text, index=0):
    text = text.lower()
    text = text.replace('.',' .')
    words = text.split()
    
    word_to_id = {}
    id_to_word = {}
    for word in words:
        if word in word_to_id:
            continue
        
        new_id = len(word_to_id)+index
        word_to_id[word] = new_id;
        id_to_word[new_id] = word;
    
    corpus = np.array([word_to_id[w] for w in words])
    
    return corpus, word_to_id, id_to_word

### 텍스트 파일을 불러와 말뭉치 처리

In [52]:
file1 = open("sample_text.txt", "r") # crawling by beautifulSoup

In [53]:
text = file1.readlines()

In [55]:
text_in_line=""
for t in text:
    text_in_line += t
    

In [56]:
text_in_line

'Supervised learning (SL) is the machine learning task of learning a function that maps an input to an output based on example input-output pairs.[1] It infers a function from labeled training data consisting of a set of training examples.[2] In supervised learning, each example is a pair consisting of an input object (typically a vector) and a desired output value (also called the supervisory signal). A supervised learning algorithm analyzes the training data and produces an inferred function, which can be used for mapping new examples. An optimal scenario will allow for the algorithm to correctly determine the class labels for unseen instances. This requires the learning algorithm to generalize from the training data to unseen situations in a "reasonable" way (see inductive bias). This statistical quality of an algorithm is measured through the so-called generalization error.[3]\n\nThe parallel task in human and animal psychology is often referred to as concept learning.\n\nTo solve 

In [57]:
corpus_file, word_to_id_file, id_to_word_file = preprocess(text_in_line)

### 텍스트 파일 말뭉치 처리 결과

In [58]:
id_to_word_file

{0: 'supervised',
 1: 'learning',
 2: '(sl)',
 3: 'is',
 4: 'the',
 5: 'machine',
 6: 'task',
 7: 'of',
 8: 'a',
 9: 'function',
 10: 'that',
 11: 'maps',
 12: 'an',
 13: 'input',
 14: 'to',
 15: 'output',
 16: 'based',
 17: 'on',
 18: 'example',
 19: 'input-output',
 20: 'pairs',
 21: '.[1]',
 22: 'it',
 23: 'infers',
 24: 'from',
 25: 'labeled',
 26: 'training',
 27: 'data',
 28: 'consisting',
 29: 'set',
 30: 'examples',
 31: '.[2]',
 32: 'in',
 33: 'learning,',
 34: 'each',
 35: 'pair',
 36: 'object',
 37: '(typically',
 38: 'vector)',
 39: 'and',
 40: 'desired',
 41: 'value',
 42: '(also',
 43: 'called',
 44: 'supervisory',
 45: 'signal)',
 46: '.',
 47: 'algorithm',
 48: 'analyzes',
 49: 'produces',
 50: 'inferred',
 51: 'function,',
 52: 'which',
 53: 'can',
 54: 'be',
 55: 'used',
 56: 'for',
 57: 'mapping',
 58: 'new',
 59: 'optimal',
 60: 'scenario',
 61: 'will',
 62: 'allow',
 63: 'correctly',
 64: 'determine',
 65: 'class',
 66: 'labels',
 67: 'unseen',
 68: 'instances',
 6

In [59]:
word_to_id_file

{'supervised': 0,
 'learning': 1,
 '(sl)': 2,
 'is': 3,
 'the': 4,
 'machine': 5,
 'task': 6,
 'of': 7,
 'a': 8,
 'function': 9,
 'that': 10,
 'maps': 11,
 'an': 12,
 'input': 13,
 'to': 14,
 'output': 15,
 'based': 16,
 'on': 17,
 'example': 18,
 'input-output': 19,
 'pairs': 20,
 '.[1]': 21,
 'it': 22,
 'infers': 23,
 'from': 24,
 'labeled': 25,
 'training': 26,
 'data': 27,
 'consisting': 28,
 'set': 29,
 'examples': 30,
 '.[2]': 31,
 'in': 32,
 'learning,': 33,
 'each': 34,
 'pair': 35,
 'object': 36,
 '(typically': 37,
 'vector)': 38,
 'and': 39,
 'desired': 40,
 'value': 41,
 '(also': 42,
 'called': 43,
 'supervisory': 44,
 'signal)': 45,
 '.': 46,
 'algorithm': 47,
 'analyzes': 48,
 'produces': 49,
 'inferred': 50,
 'function,': 51,
 'which': 52,
 'can': 53,
 'be': 54,
 'used': 55,
 'for': 56,
 'mapping': 57,
 'new': 58,
 'optimal': 59,
 'scenario': 60,
 'will': 61,
 'allow': 62,
 'correctly': 63,
 'determine': 64,
 'class': 65,
 'labels': 66,
 'unseen': 67,
 'instances': 68,
 '

전처리가 보다 필요함을 알수있는데, 온점과 소괄호, 대괄호, 쌍따옴표가 눈에 띄인다. 문서의 종류에 따라 다르겠지만 숫자도 언어처리에는 불필요 하지 않을까 생각이 된다. 

추가적으로 처리를 하자면 상대적으로 의미를 가지지 않는 단어들이 있는데 be동사나 전치사 등이 그렇다. 이런 경우에도 삭제해주어도 문서의 뜻을 해치지 않을 것이라고 생각된다.

In [62]:
corpus_file = corpus_file.astype('int32')

In [63]:
corpus_file

array([  0,   1,   2,   3,   4,   5,   1,   6,   7,   1,   8,   9,  10,
        11,  12,  13,  14,  12,  15,  16,  17,  18,  19,  20,  21,  22,
        23,   8,   9,  24,  25,  26,  27,  28,   7,   8,  29,   7,  26,
        30,  31,  32,   0,  33,  34,  18,   3,   8,  35,  28,   7,  12,
        13,  36,  37,   8,  38,  39,   8,  40,  15,  41,  42,  43,   4,
        44,  45,  46,   8,   0,   1,  47,  48,   4,  26,  27,  39,  49,
        12,  50,  51,  52,  53,  54,  55,  56,  57,  58,  30,  46,  12,
        59,  60,  61,  62,  56,   4,  47,  14,  63,  64,   4,  65,  66,
        56,  67,  68,  46,  69,  70,   4,   1,  47,  14,  71,  24,   4,
        26,  27,  14,  67,  72,  32,   8,  73,  74,  75,  76,  77,  46,
        69,  78,  79,   7,  12,  47,   3,  80,  81,   4,  82,  83,  84,
        85,   4,  86,   6,  32,  87,  39,  88,  89,   3,  90,  91,  14,
        92,  93,   1,  46,  14,  94,   8,  95,  96,   7,   0,  33,  97,
        98,  14,  99,   4, 100, 101,   8, 102, 103,   7,   0,   

In [61]:
file1.close()

### 동시 발생 행렬 co-occurrence matrix

현재 단어를 기준으로 주변단어에 어떤 단어가 등장하는 지(분포가설)를 이용하여 동시발생 행렬을 만들 수 있다.(책에서는 통계 기반 기법이라고 지칭함.) 이를 이용하면 단어를 벡터로 표현 할수도 있다.

In [12]:
# you say goodbey and i say hello .의 동시발생 행렬

C = np.array([[0,1,0,0,0,0,0],
              [1,0,1,0,1,1,0],
              [0,1,0,1,0,0,0],
              [0,0,1,0,1,0,0],
              [0,1,0,1,0,0,0],
              [0,1,0,0,0,0,1],
              [0,0,0,0,0,1,0]], dtype=np.int32)

In [13]:
text = "You say goodbye and I say hello."
text = text.lower()
text = text.replace('.',' .')
words = text.split()

word_to_id = {} # 딕셔너리
id_to_word = {}

for word in words:
    if word in word_to_id:
        continue
    new_id = len(word_to_id)
    word_to_id[word] = new_id;
    id_to_word[new_id] = word;
    
corpus = [word_to_id[w] for w in words] # 문장에 담긴 단어들을 id로 표현
corpus = np.array(corpus)

In [14]:
C[0]

array([0, 1, 0, 0, 0, 0, 0])

In [15]:
C[word_to_id['you']]

array([0, 1, 0, 0, 0, 0, 0])

In [16]:
def create_co_matrix(corpus, vocab_size, window_size=1):
    corpus_size = len(corpus)
    co_matrix = np.zeros((vocab_size,vocab_size), dtype=np.int32)
    
    for idx, word_id in enumerate(corpus):
        for i in range(1, window_size+1): # 현재 단어를 기준으로 좌우 얼마나 살펴볼지
            left_idx = idx - i;
            right_idx = idx + i
            
            if left_idx>=0:
                left_word_id = corpus[left_idx]
                co_matrix[word_id][left_word_id] += 1
                
            if right_idx < corpus_size:
                right_word_id = corpus[right_idx]
                co_matrix[word_id][right_word_id] += 1
                
    return co_matrix

In [64]:
# 위에서 직접 만든 C와 같은 결과가 나오는 것을 볼수 있음.
create_co_matrix(corpus, len(word_to_id))

array([[0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0]])

In [65]:
# 텍스트 파일을 통해 생성한 말뭉치과 딕셔너리를 이용하여 동시발생 행렬을 만들어 봄
create_co_matrix(corpus_file, len(word_to_id_file))

array([[0, 4, 0, ..., 0, 0, 0],
       [4, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### 벡터간 유사도 (cosine similarity)

In [67]:
# x,y는 numpy array라고 가정
# 0으로 나누는 경우를 방지하기 위해 아주 작은 값을 더해준다

def cos_similarity(x,y, eps = 1e-8): 
    nx = x/ np.sqrt(np.sum(x**2) + eps) # x의 정규화 
    ny = y/ np.sqrt(np.sum(y**2) + eps) # y의 정규화
    return np.dot(nx, ny)

In [68]:
text = "You say goodbye and I say hello."
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)

In [69]:
c0 = C[word_to_id['you']]
c1 = C[word_to_id['i']]
print(cos_similarity(c0,c1))

0.7071067758832467


In [74]:
def most_similarity(query, word_to_id, id_to_word, word_matrix, top=5):
    # 검색어 꺼내기
    if query not in word_to_id:
        print("%s를 찾을 수 없습니다."%query)
        return
    
    print('\n[query]' + query)
    query_id = word_to_id[query]
    query_vec = word_matrix[query_id]
    
    # 코사인 유사도 계산
    vocab_size = len(id_to_word)
    similarity = np.zeros(vocab_size)
    for i in range(vocab_size):
        similarity[i] = cos_similarity(word_matrix[i], query_vec)
        
    # 코사인 유사도를 기준으로 내림차순 ㄱ출력
    count=0
    for i in(-1 * similarity).argsort(): # 오름차순 정렬& 배열의 인덱스를 리턴
        if id_to_word[i] == query:
            continue
            
        print(" %s: %s" %(id_to_word[i], similarity[i]))
        
        count+=1
        if count>= top:
            return
    

In [75]:
# you say goodbye and i say hello 문장을 분석한 결과

most_similarity('you', word_to_id, id_to_word, C, top=5)


[query]you
 goodbye: 0.7071067758832467
 i: 0.7071067758832467
 hello: 0.7071067758832467
 say: 0.0
 and: 0.0


In [78]:
# widipedia에서 supervised learning에 단 문서 일부를 사용한 결과

C = create_co_matrix(corpus_file, len(word_to_id_file))
most_similarity('learning', word_to_id_file, id_to_word_file, C, top=10)


[query]learning
 learning:: 0.6255432405393724
 analyzes: 0.5212860337828102
 in: 0.5128776442199862
 learning,: 0.481543411889449
 is: 0.45178123028239386
 all: 0.4170288270262482
 of: 0.36265926023759854
 to: 0.3127716209647342
 set: 0.3127716202696862
 an: 0.2580234231623917


위의 결과를 보면 전처리가 더 필요함을 알수 있다.