# 2-1 Review of 1st story of this book #

### broadcasting ###

In [1]:
import numpy as np

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20]]).T

In [4]:
a

array([[1, 2],
       [3, 4]])

In [14]:
b

array([[10],
       [20]])

In [13]:
a*b

array([[10, 20],
       [60, 80]])

### inner product ###

같은위치 숫자들의 곱의 합. 두 벡터가 얼마나 같은 방향을 향하고 있는가. 같은 방향이면 1, 반대 방향이면 -1.

!np.dot(A,B) / np.matmul(A,B) 이 다름에 주의!

내적을 계산할때는 dot product를 해야함.
